---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
    category: "categories"
    tag: "tags"
buildDrafts: false
baseurl: "http://rocketbound.github.io/blog"
canonifyurls: true
theme: "hyde"
params:
    title: "Rocket Bound"
    Description: "The journey of a recoverning porn addict"
---
