contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

BaseURL = "http://rocketbound.github.io/blog"
canonifyurls = true
languageCode = "en-us"
MetaDataFormat = "toml"
title = "Rocket Bound"
theme = "hyde-x"
disqusShortname = "rocketbound"
buildDrafts = false
paginate = 10

[author]
    name = "Rocket Bound"

[params]
    truncate = false

    tagline = "The journey of a recovering porn addict"
    theme = "theme-base-0c"

    googleAnalytics = "UA-64734978-1"

[indexes] 
    category = "categories"
