---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
theme: "hyde"
indexes:
  category: "categories"
baseurl: "http://rocketbound.github.io/blog"
title: "Rocket Bound"
canonifyurls: true
---
